### PR TITLE
CI and improvements

### PR DESCRIPTION
**Pull request by hannesa2**

### CODE REVIEW

**Comment by chbeer** [comment]
Cool! Thank you very much!

**Comment by hannesa2** [comment]
But I'm confused why the Github CI doesn't start ?

**Comment by chbeer** [comment]
It's not enabled.

**Comment by hannesa2** [comment]
To avoid inflation of forks, please consider to bring this to your upstream as well.
Is there something against this ?

**Comment by chbeer** [comment]
I'm not sure I understand. What exactly do you mean by "your upstream"?

**Comment by hannesa2** [comment]
To this one https://github.com/eklipse2k8/MGScopeBar

image

**Comment by chbeer** [comment]
That's not mine

**Pull request merged**
